/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	eventmeshv1 "github.com/crain-cn/event-mesh/pkg/k8s/apis/eventmesh/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEventRoutes implements EventRouteInterface
type FakeEventRoutes struct {
	Fake *FakeEventmeshV1
	ns   string
}

var eventroutesResource = schema.GroupVersionResource{Group: "eventmesh", Version: "v1", Resource: "eventroutes"}

var eventroutesKind = schema.GroupVersionKind{Group: "eventmesh", Version: "v1", Kind: "EventRoute"}

// Get takes name of the eventRoute, and returns the corresponding eventRoute object, and an error if there is any.
func (c *FakeEventRoutes) Get(ctx context.Context, name string, options v1.GetOptions) (result *eventmeshv1.EventRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(eventroutesResource, c.ns, name), &eventmeshv1.EventRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*eventmeshv1.EventRoute), err
}

// List takes label and field selectors, and returns the list of EventRoutes that match those selectors.
func (c *FakeEventRoutes) List(ctx context.Context, opts v1.ListOptions) (result *eventmeshv1.EventRouteList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(eventroutesResource, eventroutesKind, c.ns, opts), &eventmeshv1.EventRouteList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &eventmeshv1.EventRouteList{ListMeta: obj.(*eventmeshv1.EventRouteList).ListMeta}
	for _, item := range obj.(*eventmeshv1.EventRouteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested eventRoutes.
func (c *FakeEventRoutes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(eventroutesResource, c.ns, opts))

}

// Create takes the representation of a eventRoute and creates it.  Returns the server's representation of the eventRoute, and an error, if there is any.
func (c *FakeEventRoutes) Create(ctx context.Context, eventRoute *eventmeshv1.EventRoute, opts v1.CreateOptions) (result *eventmeshv1.EventRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(eventroutesResource, c.ns, eventRoute), &eventmeshv1.EventRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*eventmeshv1.EventRoute), err
}

// Update takes the representation of a eventRoute and updates it. Returns the server's representation of the eventRoute, and an error, if there is any.
func (c *FakeEventRoutes) Update(ctx context.Context, eventRoute *eventmeshv1.EventRoute, opts v1.UpdateOptions) (result *eventmeshv1.EventRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(eventroutesResource, c.ns, eventRoute), &eventmeshv1.EventRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*eventmeshv1.EventRoute), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEventRoutes) UpdateStatus(ctx context.Context, eventRoute *eventmeshv1.EventRoute, opts v1.UpdateOptions) (*eventmeshv1.EventRoute, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(eventroutesResource, "status", c.ns, eventRoute), &eventmeshv1.EventRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*eventmeshv1.EventRoute), err
}

// Delete takes name of the eventRoute and deletes it. Returns an error if one occurs.
func (c *FakeEventRoutes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(eventroutesResource, c.ns, name), &eventmeshv1.EventRoute{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEventRoutes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(eventroutesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &eventmeshv1.EventRouteList{})
	return err
}

// Patch applies the patch and returns the patched eventRoute.
func (c *FakeEventRoutes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *eventmeshv1.EventRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(eventroutesResource, c.ns, name, pt, data, subresources...), &eventmeshv1.EventRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*eventmeshv1.EventRoute), err
}
