/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	eventmeshv1 "github.com/crain-cn/event-mesh/pkg/k8s/apis/eventmesh/v1"
	versioned "github.com/crain-cn/event-mesh/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/crain-cn/event-mesh/pkg/k8s/client/informers/externalversions/internalinterfaces"
	v1 "github.com/crain-cn/event-mesh/pkg/k8s/client/listers/eventmesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EventRouteInformer provides access to a shared informer and lister for
// EventRoutes.
type EventRouteInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.EventRouteLister
}

type eventRouteInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEventRouteInformer constructs a new informer for EventRoute type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEventRouteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEventRouteInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEventRouteInformer constructs a new informer for EventRoute type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEventRouteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EventmeshV1().EventRoutes(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EventmeshV1().EventRoutes(namespace).Watch(context.TODO(), options)
			},
		},
		&eventmeshv1.EventRoute{},
		resyncPeriod,
		indexers,
	)
}

func (f *eventRouteInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEventRouteInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *eventRouteInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&eventmeshv1.EventRoute{}, f.defaultInformer)
}

func (f *eventRouteInformer) Lister() v1.EventRouteLister {
	return v1.NewEventRouteLister(f.Informer().GetIndexer())
}
