/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/crain-cn/event-mesh/pkg/k8s/apis/eventmesh/v1"
	scheme "github.com/crain-cn/event-mesh/pkg/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EventRoutesGetter has a method to return a EventRouteInterface.
// A group's client should implement this interface.
type EventRoutesGetter interface {
	EventRoutes(namespace string) EventRouteInterface
}

// EventRouteInterface has methods to work with EventRoute resources.
type EventRouteInterface interface {
	Create(ctx context.Context, eventRoute *v1.EventRoute, opts metav1.CreateOptions) (*v1.EventRoute, error)
	Update(ctx context.Context, eventRoute *v1.EventRoute, opts metav1.UpdateOptions) (*v1.EventRoute, error)
	UpdateStatus(ctx context.Context, eventRoute *v1.EventRoute, opts metav1.UpdateOptions) (*v1.EventRoute, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.EventRoute, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.EventRouteList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EventRoute, err error)
	EventRouteExpansion
}

// eventRoutes implements EventRouteInterface
type eventRoutes struct {
	client rest.Interface
	ns     string
}

// newEventRoutes returns a EventRoutes
func newEventRoutes(c *EventmeshV1Client, namespace string) *eventRoutes {
	return &eventRoutes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the eventRoute, and returns the corresponding eventRoute object, and an error if there is any.
func (c *eventRoutes) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.EventRoute, err error) {
	result = &v1.EventRoute{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("eventroutes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EventRoutes that match those selectors.
func (c *eventRoutes) List(ctx context.Context, opts metav1.ListOptions) (result *v1.EventRouteList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.EventRouteList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("eventroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested eventRoutes.
func (c *eventRoutes) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("eventroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a eventRoute and creates it.  Returns the server's representation of the eventRoute, and an error, if there is any.
func (c *eventRoutes) Create(ctx context.Context, eventRoute *v1.EventRoute, opts metav1.CreateOptions) (result *v1.EventRoute, err error) {
	result = &v1.EventRoute{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("eventroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(eventRoute).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a eventRoute and updates it. Returns the server's representation of the eventRoute, and an error, if there is any.
func (c *eventRoutes) Update(ctx context.Context, eventRoute *v1.EventRoute, opts metav1.UpdateOptions) (result *v1.EventRoute, err error) {
	result = &v1.EventRoute{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("eventroutes").
		Name(eventRoute.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(eventRoute).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *eventRoutes) UpdateStatus(ctx context.Context, eventRoute *v1.EventRoute, opts metav1.UpdateOptions) (result *v1.EventRoute, err error) {
	result = &v1.EventRoute{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("eventroutes").
		Name(eventRoute.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(eventRoute).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the eventRoute and deletes it. Returns an error if one occurs.
func (c *eventRoutes) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("eventroutes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *eventRoutes) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("eventroutes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched eventRoute.
func (c *eventRoutes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EventRoute, err error) {
	result = &v1.EventRoute{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("eventroutes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
