/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package internalversion

import (
	v1 "github.com/crain-cn/event-mesh/pkg/k8s/apis/eventmesh/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// EventRouteLister helps list EventRoutes.
// All objects returned here must be treated as read-only.
type EventRouteLister interface {
	// List lists all EventRoutes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.EventRoute, err error)
	// Get retrieves the EventRoute from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.EventRoute, error)
	EventRouteListerExpansion
}

// eventRouteLister implements the EventRouteLister interface.
type eventRouteLister struct {
	indexer cache.Indexer
}

// NewEventRouteLister returns a new EventRouteLister.
func NewEventRouteLister(indexer cache.Indexer) EventRouteLister {
	return &eventRouteLister{indexer: indexer}
}

// List lists all EventRoutes in the indexer.
func (s *eventRouteLister) List(selector labels.Selector) (ret []*v1.EventRoute, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.EventRoute))
	})
	return ret, err
}

// Get retrieves the EventRoute from the index for a given name.
func (s *eventRouteLister) Get(name string) (*v1.EventRoute, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("eventroute"), name)
	}
	return obj.(*v1.EventRoute), nil
}
