"global":
  "resolve_timeout": "5m"
"inhibit_rules":
  - "equal":
      - "namespace"
      - "alertname"
    "source_match":
      "severity": "critical"
    "target_match_re":
      "severity": "warning|info"
  - "equal":
      - "namespace"
      - "alertname"
    "source_match":
      "severity": "warning"
    "target_match_re":
      "severity": "info"
"receivers":
  - "name": "Default"
  - "name": "Watchdog"
  - "name": "Critical"
  - "name": "webhook1"
    webhook_configs:
      - url: http://eventmesh-svc.jituan-zhongtai-iaas.svc.cluster.local:8080/apiv3/notification/v1/alert/webhook?cluster=k8s-test
        send_resolved: true
"route":
  "group_by":
    - "namespace"
  "group_interval": "1m"
  "group_wait": "10s"
  "receiver": "Default"
  "repeat_interval": "12h"
  "routes":
    - "match":
        "alertname": "Watchdog"
      "receiver": "Watchdog"
    - "match":
        "severity": "critical"
      "receiver": "webhook1"
    - "match":
        "severity": "warning"
      "receiver": "webhook1"
