package v1

func (in *EventRoute) DeepEqual(other *EventRoute) bool {
	if other == nil {
		return false
	}

	if !in.Spec.DeepEqual(&other.Spec) {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *EventRouteSpec) DeepEqual(other *EventRouteSpec) bool {
	if other == nil {
		return false
	}

	return true
}
