databases:
  - name: mysql
    mysql:
      host: 127.0.0.1
      port: 3306
      username: other_rw
      database: k8s_notification
      password: xxxxxxxxx
    labels:
      env: test
  - name: mysql_platform
    mysql:
      host: 127.0.0.1
      port: 6306
      username: other_rw
      database: k8s_notification
      password: xxxxxxxxx
    labels:
      env: test
