databases:
  - name: mysql
    mysql:
      host: 127.0.0.1
      port: 3306
      username: other_rw
      database: k8s_notification
      password: xxxxxxxxxxx
    labels:
      env: online
  - name: mysql_platform
    mysql:
      host: 127.0.0.1
      port: 3306
      username: k8s_pla_rw
      database: k8s_platform
      password: xxxxxxxxxxx
    labels:
      env: online